# Best practice to create a ServiceAccount for each agent to allow for more granular permissions if needed.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weather-tool
  namespace: team1
---
# Expose the MCP endpoint
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: weather-tool
    # rossoctl.io/type=tool is required for the MCP Server that provides tool to be discovered by Rossoctl and show up in the UI
    rossoctl.io/type: tool
    protocol.rossoctl.io/mcp: ""
  name: weather-tool-mcp
  namespace: team1
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: weather-tool
    rossoctl.io/type: tool
  type: ClusterIP
---
# Deploy a test build of the Tool
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: weather-tool
    rossoctl.io/framework: Python
    # Set inject to true for [AuthBridge](https://github.com/rossoctl/cortex/tree/main/AuthBridge)
    rossoctl.io/inject: disabled
    rossoctl.io/type: tool
    rossoctl.io/workload-type: deployment
    protocol.rossoctl.io/mcp: ""
  name: weather-tool
  namespace: team1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: weather-tool
      rossoctl.io/type: tool
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weather-tool
        rossoctl.io/framework: Python
        # Set inject to true for [AuthBridge](https://github.com/rossoctl/cortex/tree/main/AuthBridge)
        rossoctl.io/inject: disabled
        rossoctl.io/transport: streamable_http
        rossoctl.io/type: tool
        protocol.rossoctl.io/mcp: ""
    spec:
      containers:
      - env:
        # Port to bind MCP server
        - name: PORT
          value: "8000"
        # Host to bind MCP server (0.0.0.0 means bind to all interfaces)
        - name: HOST
          value: 0.0.0.0
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector.rossoctl-system.svc.cluster.local:8335
        - name: KEYCLOAK_URL
          value: http://keycloak.keycloak.svc.cluster.local:8080
        - name: UV_CACHE_DIR
          value: /app/.cache/uv
        # Pin to a specific version
        image: ghcr.io/rossoctl/examples/weather_tool:v0.1.0-alpha.1
        # Or use the latest version
        # image: ghcr.io/rossoctl/examples/weather_tool:latest
        imagePullPolicy: Always
        name: mcp
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        # Note that a readinessProbe is recommended.  Rossoctl doesn't generate one for UI
        # deployments, and we follow that pattern in this example, but you may want to add one for your own tools.
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        # This is for agents that use uv and its dependency cache
        - mountPath: /app/.cache
          name: cache
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: weather-tool
      terminationGracePeriodSeconds: 30
      volumes:
      # This is for tools that use uv and its dependency cache
      - emptyDir: {}
        name: cache
      - emptyDir: {}
        name: tmp
