FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim
ARG RELEASE_VERSION="main"

COPY . /app
WORKDIR /app

RUN uv sync --no-cache --locked --link-mode copy

ENV PRODUCTION_MODE=True \
    RELEASE_VERSION=${RELEASE_VERSION} \
    PATH="/app/.venv/bin:$PATH"

RUN chown -R 1001:1001 /app
USER 1001

CMD ["uv", "run", "--no-sync", "app", "--host", "0.0.0.0", "--port", "8000"]
